align=center
separator=false
markup=pango
separator_block_width=25

[time]
command=~/.config/i3/scripts/time.nim
interval=1

[battery]
command=~/.config/i3/scripts/battery.nim
label=
interval=5

[ppd_menu]
full_text=" profile "
command=~/.config/i3/scripts/power_profiles.sh
interval=5

[volume-pulseaudio]
command=~/.config/i3/scripts/volume.nim
instance=Master
interval=1
timeout=10
signal=12

[brightness]
full_text=" brightness "
command=~/projects/scripts/i3block/brightness.nim
interval=once
signal=10

[click-daysoff]
full_text=" daysoff "
command=~/work/scripts/days_off.sh

[shutdown_menu]
full_text=" power "
command=~/.config/i3/scripts/power_menu.sh

