alias ccal="cal -mn 3 $*"
alias update-discord="yes | yay -Sy discord $*"
alias la="ls -a --color=auto --group-directories-first $*"
alias ll="ls -al --color=auto --group-directories-first $*"
alias activate=". ./.venv/bin/activate"
alias lsub="~/projects/lsub.sh $*"
alias noswap="rm ~/.local/state/nvim/swap/* $*"
alias ocli="~/projects/ocli.sh $*"
alias daysoff="~/projects/scripts/daysoff.py $*"
alias pg="pgcli -d odoodb $*"
alias pac="yes | sudo pacman -Scc && sudo pacman -Su $*"
alias pr="~/projects/scripts/pr.sh $*"
alias rgg="rg -in -C3 --max-depth 5 --no-heading --type=xml --type=py $*"
alias rv="~/projects/reviewtui.sh $*"
alias tran="~/projects/translate/traduire.py $*"
alias starter="cd ~/projects/starter 1>/dev/null 2>/dev/null && . ./starter.sh $*"
alias system-update="yes | sudo pacman -Sy endeavouros-keyring && sudo pacman -Syu $*"
alias starter=". ~/projects/starter.sh $*"
alias note="echo '$*' >> ~/notes.txt"
alias notes="tail $* ~/notes.txt"
alias py="ipython3 $*"
alias reload=". ~/.bashrc $*"
alias realias=". ~/.bash_aliases $*"
alias v="~/projects/venv.sh $*"
alias k="source ~/projects/scripts/k.sh"
