alias ..="cd .. $*"
alias ccal="cal -mn 3 $*"
alias la="ls -a --color=auto --group-directories-first $*"
alias ll="ls -al --color=auto --group-directories-first $*"
alias activate=". ./.venv/bin/activate"
alias lsub="~/projects/lsub/lsub.py $*"
alias noswap="rm ~/.local/state/nvim/swap/* $*"
alias pg="pgcli -d odoodb $*"
alias pac="yes | sudo pacman -Scc && sudo pacman -Su $*"
alias pr="~/projects/scripts/pr.sh $*"
alias rgg="rg -in -C3 --max-depth 5 --no-heading --type=xml --type=py $*"
alias rv="~/projects/reviews/reviews.sh lordkrandel"
alias tran="~/projects/translate/traduire.py $*"
alias system-update="sudo pacman -Sy endeavouros-keyring && sudo pacman -Syu $*"
alias starter="cd ~/projects/starter 1>/dev/null 2>/dev/null && . ./starter.sh $*"
alias py="ipython3 $*"
alias reload=". ~/.bashrc $*"
